version: "3"
services:
  psql_docker:
    image: postgres:12.0-alpine
    container_name: psql_docker
    ports:
      - "5432:5432"
    environment:
       POSTGRES_USER: "dev"
       POSTGRES_PASSWORD: "dev"
       POSTGRES_DB: "mydb"
